name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        type: string
        default: 'test'
      age:
        description: 'Age'
        type: number
        required: true
      gender:
        description: 'Gender'
        type: choice
        options:
          - Male
          - Female
      married:
          description: 'Is married?'
          type: boolean
          
jobs:
  manual:
    runs-on: ubuntu-latest
    
    steps:
      - name: Greetings
        run: echo "Hello ${{ inputs.name }}!"

      - name: Age 
        run: echo "Hello ${{ inputs.Age }}!"

      - name: Gender 
        run: echo "Hello ${{ inputs.Gender }}!"

      - name: married
        run: echo "Hello ${{ inputs.maried }}!"
        
     
      
